version: '3.7'
services:
  proxy:
    image: 'bahmni/proxy:${PROXY_IMAGE_TAG:?}'
    volumes:
      #   - ${CERTIFICATE_PATH}:/etc/tls
      - 'bahmni-patient-images:/home/bahmni/patient_images'
      - 'bahmni-document-images:/home/bahmni/document_images'

    ports:
      - '80:80'
      - '443:443'
  bahmni-lab:
    image: 'bahmni/bahmni-lab:${BAHMNI_LAB_IMAGE_TAG:?}'
    ports:
      - '8090:80'
      - '8443:443'

  openmrs:
    profiles: ['default', 'openmrs']
    image: bahmni/openmrs:${OPENMRS_IMAGE_TAG:?}
    environment:
      DB_DATABASE: ${OPENMRS_DB_NAME:?}
      DB_HOST: ${OPENMRS_DB_HOST:?}
      DB_USERNAME: ${MYSQL_ROOT_USERNAME:?}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      DB_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME:?}
      DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      DB_CREATE_TABLES: ${OPENMRS_DB_CREATE_TABLES}
      DB_AUTO_UPDATE: ${OPENMRS_DB_AUTO_UPDATE}
      LOAD_DEMO_DATA: ${OPENMRS_LOAD_DEMO_DATA}
      DB_DUMP_GZIP_URL: ${OPENMRS_DB_DUMP_GZIP_URL}
      MODULE_WEB_ADMIN: ${OPENMRS_MODULE_WEB_ADMIN}
      DEBUG: ${OPENMRS_DEBUG}
      OPENELIS_HOST: ${OPENELIS_HOST:?}
      OPENELIS_PORT: ${OPENELIS_PORT:?}
      OPENELIS_ATOMFEED_USER: ${OPENELIS_ATOMFEED_USER:?}
      OPENELIS_ATOMFEED_PASSWORD: ${OPENELIS_ATOMFEED_PASSWORD:?}
    ports:
      - '8080:8080'
    volumes:
      # - 'openmrs-data:/usr/local/tomcat/.OpenMRS/modules'
      # - '${BAHMNI_OPENMRS_MODULES_PATH:?}/:/usr/local/tomcat/.OpenMRS/modules/'
      - '${BAHMNI_CONFIG_PATH:?}/:/etc/bahmni_config/'
      - '${BAHMNI_CONFIG_PATH:?}/masterdata/configuration/:/usr/local/tomcat/.OpenMRS/configuration/'
      - 'bahmni-patient-images:/home/bahmni/patient_images'
      - 'bahmni-document-images:/home/bahmni/document_images'
    depends_on:
      - openmrsdb

  openmrsdb:
    image: mysql:5.6
    restart: always
    profiles: ["default","openmrs"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
    ports:
      - '3306:3306'
    volumes:
      - 'openmrsdbdata:/var/lib/mysql'

  bahmni-web:
    image: bahmni/bahmni-web:${BAHMNI_WEB_IMAGE_TAG:?}
    profiles: ['default', 'openmrs']
    volumes:
      #- "${BAHMNI_APPS_PATH:?}/ui/app/:/usr/local/apache2/htdocs/bahmni"
      #- "${BAHMNI_APPS_PATH:?}/ui/node_modules/@bower_components/:/usr/local/apache2/htdocs/bahmni/components"
      - '${BAHMNI_CONFIG_PATH:?}/:/usr/local/apache2/htdocs/bahmni_config/'

volumes:
  openmrs-data:
  openmrsdbdata:
  bahmni-patient-images:
  bahmni-document-images:
