name: clinic-config deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: extract private key
        run: 'echo "$SSH_KEY" > bahmni-clinic-demo.pem'
        shell: bash
        env:
          SSH_KEY: ${{secrets.BAHMNI_CLINIC_PEM}}
      - name: deploy clinic configuration
        run: |
          sudo ssh -T -o "StrictHostKeyChecking no" -i "bahmni-clinic-demo.pem" ec2-user@ec2-3-110-214-169.ap-south-1.compute.amazonaws.com <<EOF
            rm -rf clinic-config
            git clone https://github.com/BahmniIndiaDistro/clinic-config.git
            cd clinic-config/package/docker
            docker-compose restart openmrs
          EOF
  notification:
    name: notification
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy notification
        if: ${{ needs.deploy.result == 'success' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":":white_check_mark:  Clinic configuration deployed on https://clinics.bahmni-covid19.in/"}' ${{ secrets.SLACK_WEBHOOK_URL }}
